language: node_js
cache:
  directories:
    - "node_modules"

node_js:
- "node"

sudo: false
services:
 - docker
before_script:
  - npm install

script:
 - npm run build

after_success:
  - bin/docker_push.sh
